unix: Try disable VFS
Was hoping this could help fix executing a file
But instead open() etc breaks with things like

	OSError: stream operation not supported
	Error: Dynamic linking error: cannot resolve symbol mp_import_stat